package org.am21.model.enumer;

public enum ServerMessage {
    ConnectionSuccessful("Server > Connection successful"),
    ConnectionFailed(""),
    LoginSuccessful(""),
    LoginFailed(""),
    CreateMatchSuccessful(""),
    CreateMatchFailed(""),
    JoinMatchSuccessful(""),
    JoinMatchFailed(""),
    UserLeaveGame(""),
    SavedUserData(""),
    FindingMatchAvailable(""),
    MatchFound(""),
    MatchNotFound(""),
    GeneratingRoom(""),
    NumberPlayerSelected(""),
    ChoseNumberPlayer(""),
    WaitingForPlayers(""),
    BuildingBoardPleaseWait(""),
    BoardSuccessfulBuild(""),
    BoardBuildFailed(""),
    TheseAreTheCommonGoals(""),
    ThisIsYourPersonalGoal(""),
    TheGameBegins(""),
    ItIsYourTurn(""),
    NotYourTurn(""),
    PleaseSelectAnItemOnTheBoard(""),
    SelectionSuccessful(""),
    SelectionFailed(""),
    AllCardAreSelected(""),
    ChoseACellOnTheBoard(""),
    WhichCellWriteTheCoordinates(""),
    TheCellIsEmpty(""),
    TheCellIsNotSelectable(""),
    AlreadySelected(""),
    YourHandIsFull(""),
    YouCanSelected_3_Cards(""),
    YouCanSelected_2_Cards(""),
    YouCanSelected_1_Card(""),
    YouCanNotInsertCardsIfYouDidNotSelectAny(""),
    DoYouWantToChangeInsertionOrder(""),
    WitchCardsShouldSwitch(""),
    CardOrderChanged(""),
    SelectColumnToInsert(""),
    ColumnNotAvailable(""),
    GoalAchieved(""),
    Points(""),
    YouMatchedAnItem(""),
    HereIsTheBoard(""),
    HereIsTheShelf(""),
    HereIsTheCommonGoal(""),
    HereIsThePersonalGoal(""),
    HereIsThePlayersStats(""),
    HereIsTheEndGameToken(""),
    RunOutOfTime(""),
    WrongPhase(""),
    GameOver(""),
    YouWon(""),
    YouAreTheSecond(""),
    YouAreTheThird(""),
    YouAreTheFourth(""),
    Error(""),
    WriteMessage(""),
    ChatHistory("");

    ServerMessage(String s) {

    }

    public static void printMessage(ServerMessage value){
        System.out.println(value);
    }
}
